# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TerrainGeneration

QT += core widgets gui opengl
CONFIG += debug

include(TerrainGeneration.pri)
